# Generated by Django 5.2.4 on 2025-08-17 18:58

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to=apps.menu.models.category_image_path, verbose_name='Imagen de Categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marcar si la categoría está activa', verbose_name='Activa'),
        ),
    ]
