# Generated by Django 5.1.7 on 2025-04-05 03:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista de categorías', verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_allergen', models.BooleanField(default=False, verbose_name='alérgeno')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Tiempo estimado de preparación en minutos', verbose_name='tiempo de preparación (min)')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Cantidad de calorías por porción', null=True, verbose_name='calorías')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, help_text='Ej: 100g, 2 cucharadas, etc.', max_length=50, verbose_name='cantidad')),
                ('is_optional', models.BooleanField(default=False, verbose_name='opcional')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio extra')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.dish', verbose_name='plato')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.ingredient', verbose_name='ingrediente')),
            ],
            options={
                'verbose_name': 'ingrediente del plato',
                'verbose_name_plural': 'ingredientes del plato',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto fijo')], default='PERCENTAGE', max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor del descuento')),
                ('start_date', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('dishes', models.ManyToManyField(blank=True, related_name='promotions', to='menu.dish', verbose_name='platos')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificación')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.dish', verbose_name='plato')),
            ],
            options={
                'verbose_name': 'reseña',
                'verbose_name_plural': 'reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
