# Generated by Django 5.1.7 on 2025-04-05 03:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'ítem de carrito',
                'verbose_name_plural': 'ítems de carrito',
            },
        ),
        migrations.CreateModel(
            name='CartItemCustomization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include', models.BooleanField(default=True, help_text='Indica si se debe incluir o excluir este ingrediente', verbose_name='incluir')),
                ('extra', models.BooleanField(default=False, help_text='Indica si se debe agregar extra de este ingrediente', verbose_name='extra')),
            ],
            options={
                'verbose_name': 'personalización de ítem',
                'verbose_name_plural': 'personalizaciones de ítems',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'En preparación'), ('READY', 'Listo para entrega'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Recoger en restaurante'), ('DELIVERY', 'Entrega a domicilio')], default='PICKUP', max_length=20, verbose_name='método de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='impuesto')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo de entrega')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas adicionales')),
                ('expected_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='tiempo estimado de entrega')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID de pago')),
                ('payment_status', models.CharField(blank=True, max_length=50, verbose_name='estado de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=200, verbose_name='nombre del plato')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio total')),
                ('notes', models.TextField(blank=True, verbose_name='notas adicionales')),
            ],
            options={
                'verbose_name': 'ítem de pedido',
                'verbose_name_plural': 'ítems de pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100, verbose_name='nombre del ingrediente')),
                ('include', models.BooleanField(default=True, verbose_name='incluir')),
                ('extra', models.BooleanField(default=False, verbose_name='extra')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio extra')),
            ],
            options={
                'verbose_name': 'personalización de ítem de pedido',
                'verbose_name_plural': 'personalizaciones de ítems de pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'En preparación'), ('READY', 'Listo para entrega'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'historial de estado de pedido',
                'verbose_name_plural': 'historial de estados de pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
